jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GIT_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: echo "Using GIT_TOKEN"
